# Generated by Django 4.0.2 on 2022-06-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='EMAIL_FIELD',
        ),
    ]
