# Generated by Django 4.0.2 on 2022-06-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_email_user_email_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='EMAIL_FIELD',
            new_name='email_field',
        ),
    ]
