# Generated by Django 4.0.2 on 2022-06-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_email_field_user_email_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='EMAIL_FIELD',
            new_name='email',
        ),
    ]
