# Generated by Django 4.0.2 on 2022-03-30 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0002_purchasedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedproducts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
