# Generated by Django 4.0.2 on 2022-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0004_ordermodel_delete_purchasedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
