# Generated by Django 4.0.2 on 2022-04-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0005_ordermodel_street'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdModels',
            new_name='AdModel',
        ),
    ]
