# Generated by Django 4.0.2 on 2022-04-22 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_system', '0008_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name_plural': 'All Images'},
        ),
        migrations.AlterModelOptions(
            name='orderedproductmodel',
            options={'verbose_name_plural': 'All Ordered Products'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
