# Generated by Django 4.0.2 on 2022-07-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0015_alter_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admodel',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNISEX')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admodel',
            name='movement_type',
            field=models.CharField(choices=[('A', 'Automatic'), ('D', 'Digital'), ('A', 'Automatic'), ('SE', 'Solar/Eco-Drive'), ('Q', 'Quartz'), ('H', 'Hand Wind')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
