# Generated by Django 4.0.2 on 2022-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_system', '0016_admodel_gender_admodel_movement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admodel',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='orderedproductmodel',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admodel',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unisex', 'UNISEX')], max_length=6),
        ),
        migrations.AlterField(
            model_name='admodel',
            name='movement_type',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('digital', 'Digital'), ('solar/eco-drive', 'Solar/Eco-Drive'), ('quartz', 'Quartz'), ('hand wind', 'Hand Wind')], max_length=15),
        ),
    ]
